### ISSUE TITLE
Error when when rendering collections is disabled

### ISSUE THREAD

**Issue by PoetikDragon** [zfcampus/zf-apigility#25]
In my config I set $config['zf-hal']['render_collections'] = false in order to bandaid a problem with recursive entity reference. However, when I do so, the Apigility admin stops working. The main section of /apigility/ui#/api is blank. The javascript console displays this error:

```
TypeError: Cannot call method 'pop' of undefined
    at http://localhost:8080/zf-apigility-admin/js/app.js:1:5390
    at Array.forEach (native)
    at Object.f [as forEach] (http://localhost:8080/zf-apigility-admin/js/vendor-angular.js:1:1005)
    at f (http://localhost:8080/zf-apigility-admin/js/app.js:1:5326)
    at new <anonymous> (http://localhost:8080/zf-apigility-admin/js/app.js:1:5869)
    at d (http://localhost:8080/zf-apigility-admin/js/vendor-angular.js:1:15787)
    at Object.e [as instantiate] (http://localhost:8080/zf-apigility-admin/js/vendor-angular.js:1:15899)
    at http://localhost:8080/zf-apigility-admin/js/vendor-angular.js:1:32078
    at q (http://localhost:8080/zf-apigility-admin/js/vendor-angular.js:4:23001)
    at A (http://localhost:8080/zf-apigility-admin/js/vendor-angular.js:4:23362)
```

Not really sure if I should be posting this in zf-apigility or zf-hal, but they're both zfcampus modules so I'll let you guys sort it out.

**Comment by michalbundyra** [comment]
This repository has been closed and moved to laminas-api-tools/api-tools; a new issue has been opened at https://github.com/laminas-api-tools/api-tools/issues/74.
